### ISSUE TITLE
Queue and thread pool could be separate classes

### ISSUE THREAD

**Issue by jbradt** [ExtremeScale/ThreadPool#3]
I'm working on separating the two. This allows us to have a template class for the queue, which seems like it will be more flexible if we want to try different callables, etc.

I'm planning on making the syntax for the new queue class be identical to that of the std::queue class, for consistency.

**Comment by csullivan** [comment]
I think this will be important for cases in which the number of tasks >> the number of threads, because a task queue of std::functions will be slower than regular function calls, but for the current ParallelFor implementation, I think it's ok because the number of tasks == the number of threads, and the overhead of a std::function in that case is quite small. 

Re: separating the pool and queue: I assume in that case you will then move all the semaphore/locks etc into the templated queue class?

**Comment by jbradt** [comment]
Yeah, I'm moving them over. It seems more tidy to me to not force the thread pool to deal with the locks on the queue. (I've always thought it was odd that mutexes are separate from the objects they lock, so I like to sweep them together. *shrug*)

Also I think separating these might help with the problem with the MapRange function (#2) since I might be able to try dividing up the work more rigorously (like by repackaging the data and sending it off to the threads in pieces). This will probably kill the performance, but I guess it's better than it failing like it is now.

**Comment by csullivan** [comment]
Makes sense to me. I think it's a nice idea to benchmark every step of the way so that when it comes to writing the report, it'll be pretty easy to discuss different ways we did things and how it affected performance.

Thus, I think we should probably have a couple of benchmarks as unit tests that can easily be run after compilation. Perhaps the matrix-matrix multiply is a good one?

**Comment by jbradt** [comment]
Good plan. I started to add a unit test for my MapRange function the other night, but I didn't get it working yet (the function, not the test). I was using [Catch](https://github.com/philsquared/Catch) since I happen to like that framework, but if you'd prefer a different framework, I'm open to suggestions.

Perhaps we should start another issue for the unit tests?
